package project.terminal;

/**
 * StringEntryMenu - A class which narrows the scope of the TerminalMenu to just the String Type.
 *     Additionally, it adds support to check for particular properties in the entry.
 *
 * Created by Ashton on 10/16/2016.
 */
public class StringEntryMenu extends TerminalMenu<String>{

    //Default Settings
    private final static int DEFAULT_MIN_LENGTH = 1;
    private final static int DEFAULT_MAX_LENGTH = 500;
    private final static boolean DEFAULT_ALPHABET_ONLY = false;

    //Settings
    private int minLength = DEFAULT_MIN_LENGTH;
    private int maxLength = DEFAULT_MAX_LENGTH;
    private boolean alphabetOnly = DEFAULT_ALPHABET_ONLY;

    //Constructors
    public StringEntryMenu(String name, String body, String entry_prompt, boolean alphabetOnly, int minLength, int maxLength) {
        super(name, "", body, entry_prompt);
        this.alphabetOnly = alphabetOnly;
        this.minLength = minLength;
        this.maxLength = maxLength;
    }

    public StringEntryMenu(String name, String body, String entry_prompt, int minLength, int maxLength) {
        super(name, "", body, entry_prompt);
        this.minLength = minLength;
        this.maxLength = maxLength;
    }

    public StringEntryMenu(String name, String body, String entry_prompt, boolean alphabetOnly) {
        super(name, "", body, entry_prompt);
        this.alphabetOnly = alphabetOnly;
    }

    public StringEntryMenu(String name, String body, String entry_prompt) {
        super(name, "", body, entry_prompt);
    }

    /** Overrides the default printMenu to only print the body*/
    @Override
    protected void printMenu() {
        printBody();
    }

    /**
     * Does NOT parse the input since the input is by default a String
     *
     * @param input - raw input from the user
     * @return entry
     */
    @Override
    protected String parseInputForEntry(String input) {
        return input;
    }

    /**
     * Generates a responseCode based on the settings
     *      0: Valid entry
     *     -1: Invalid Input
     *     -2: Less than minimum length
     *     -3: Greater than max length
     *     -4: If alphabet only and has non-alphabetical characters
     *
     * @return responseCode
     */
    @Override
    protected int generateEntryResponseCode() {
        int response_code = 0;
        if (entry != null) {
            if (entry.length() >= minLength) {
                if (entry.length() <= maxLength) {
                    if (alphabetOnly && !entry.matches("[a-zA-Z]"))
                        response_code = -4;
                } else
                    response_code = -3;
            } else
                response_code = -2;
        } else
            response_code = -1;
        return response_code;
    }

    /**
     * Prints the response based on the code given by generateEntryResponseCode
     *
     * @param responseCode - The response code generated by generateEntryResponseCode
     */
    @Override
    protected void printEntryResponse(int responseCode) {
        if (responseCode != 0) {
            switch (responseCode) {
                case -1:
                    System.out.println("Invalid Input!");
                    break;
                case -2:
                    System.out.println("Invalid Entry: Minimum Length is " + minLength);
                    break;
                case -3:
                    System.out.println("Invalid Entry: Maximum Length is " + maxLength);
                    break;
                case -4:
                    System.out.println("Invalid Entry: Only Alphabetical Characters");
                    break;
                default:
                    System.out.println("Unknown Error!");
            }
        }
    }
}
